[package]
name = "cargame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avian2d = "0.7.0"
bevy = "0.19.0"
# bevy-inspector-egui = { version = "0.36.0", default-features = false, features = ["bevy_render", "bevy_pbr"] }
bevy_ecs_tiled = { version = "0.13", features = ["avian", "user_properties"] }
bevy_enhanced_input = "0.26"
bevy_ui = "0.19"
rand = "0.10.0"
